name: Assign to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign new issues and pull requests to the topic tracking project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/TheProjectAurora/vault/projects/1'
